---
collections:
- name: redhat.openshift
- name: redhat.openshift_virtualization
- name: kubernetes.core
- name: rhpds.assisted_installer
  type: git
  source: https://github.com/rhpds/assisted_installer