---
- name: "Create {{ extract_dest_path }}"
  ansible.builtin.file:
    path: "{{ extract_dest_path }}"
    state: directory
    mode: 0755
    recurse: true

- name: Download openshift-install
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/fast/openshift-install-linux.tar.gz
    dest: "{{ extract_dest_path }}/"
    mode: '0755'

- name: Extract openshift-install
  ansible.builtin.unarchive:
    src: "{{ extract_dest_path }}/openshift-install-linux.tar.gz"
    dest: "{{ extract_dest_path }}/"

- name: Check extracted installer has agent subcommand
  ansible.builtin.shell:
    cmd: "{{ openshift_installer_path }} agent --help"
  register: result
  failed_when: '"No such" in result.stderr'

- name: Check agent sub-commmand output
  ansible.builtin.fail:
    msg: >
      Version of openshift install extracted from
      release image does not have agent subcommand
  when: "'unknown command' in result.stderr"

- name: Set agent_based_installer_path
  ansible.builtin.set_fact:
    agent_based_installer_path: "{{ openshift_installer_path }}"

- name: ls openshift-install path
  ansible.builtin.shell:
    cmd: "ls -lh {{ extract_dest_path }}"