- name: Playbook for Kubernetes tasks
  hosts: localhost
  collections:
    - kubernetes.core
  tasks:
  - name: Create a pod
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: testpod-1
          namespace: default
          labels:
            app: ansible-tests
        spec:
          containers:
            - name: testcontainer
              image: busybox